# Generated by Django 6.0.5 on 2026-05-09 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_no', models.CharField(blank=True, max_length=100, null=True)),
                ('uif_no', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=13, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('join_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('bank_details', models.JSONField(blank=True, null=True)),
                ('tax_directive_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='payroll.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.IntegerField()),
                ('period_year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='payroll.organization')),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.taxyear')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('uif', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sdl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pdf_storage_path', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_taxable', models.BooleanField(default=True)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payslip')),
            ],
        ),
        migrations.CreateModel(
            name='TaxThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_under_65', models.DecimalField(decimal_places=2, max_digits=12)),
                ('age_65_to_75', models.DecimalField(decimal_places=2, max_digits=12)),
                ('age_75_over', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_thresholds', to='payroll.taxyear')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary (65+)'), ('tertiary', 'Tertiary (75+)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rebates', to='payroll.taxyear')),
            ],
        ),
        migrations.CreateModel(
            name='PAYEBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paye_brackets', to='payroll.taxyear')),
            ],
            options={
                'ordering': ['from_amount'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dependent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('second_dependent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_dependents', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_credit', to='payroll.taxyear')),
            ],
        ),
        migrations.CreateModel(
            name='UIFConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('employee_cap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_cap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uif_config', to='payroll.taxyear')),
            ],
        ),
    ]
