# Generated by Django 6.0.5 on 2026-05-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eti_months_claimed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='eti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ETIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField()),
                ('range_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('range_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('excess_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('excess_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eti_configs', to='payroll.taxyear')),
            ],
        ),
    ]
