# Generated by Django 6.0.5 on 2026-05-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_eti_months_claimed_payslip_eti_eticonfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='medical_dependents',
            field=models.IntegerField(default=0),
        ),
    ]
