# Generated by Django 6.0.5 on 2026-05-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_medical_dependents'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDLConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('annual_threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdl_config', to='payroll.taxyear')),
            ],
        ),
    ]
